apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "leilfs-operator.fullname" . }}-manager-role
  labels:
    {{- include "leilfs-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - persistentvolumeclaims
      - services
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources:
      - daemonsets
      - deployments
      - statefulsets
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [leilfs.leilfs-operator.io]
    resources:
      - leilfsclusters
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [leilfs.leilfs-operator.io]
    resources:
      - leilfsclusters/finalizers
    verbs: [update]
  - apiGroups: [leilfs.leilfs-operator.io]
    resources:
      - leilfsclusters/status
    verbs: [get, patch, update]
