# permissions for end users to edit leilfsclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: leilfscluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: leilfs-operator
    app.kubernetes.io/part-of: leilfs-operator
    app.kubernetes.io/managed-by: kustomize
  name: leilfscluster-editor-role
rules:
- apiGroups:
  - leilfs.leilfs-operator.io
  resources:
  - leilfsclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - leilfs.leilfs-operator.io
  resources:
  - leilfsclusters/status
  verbs:
  - get
