kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: saunafs-operator
nodes:
  - role: control-plane

  # worker — hosts the SaunaFS master (via nodeSelector saunafs-role=master)
  # and two chunk servers (one per disk).
  - role: worker
    labels:
      saunafs-role: master
    extraMounts:
      - hostPath: /tmp/saunafs-kind/worker1/hdd001
        containerPath: /mnt/hdd001
      - hostPath: /tmp/saunafs-kind/worker1/hdd002
        containerPath: /mnt/hdd002

  # worker2 — two chunk servers (one per disk).
  - role: worker
    extraMounts:
      - hostPath: /tmp/saunafs-kind/worker2/hdd001
        containerPath: /mnt/hdd001
      - hostPath: /tmp/saunafs-kind/worker2/hdd002
        containerPath: /mnt/hdd002

  # worker3 — two chunk servers (one per disk).
  - role: worker
    extraMounts:
      - hostPath: /tmp/saunafs-kind/worker3/hdd001
        containerPath: /mnt/hdd001
      - hostPath: /tmp/saunafs-kind/worker3/hdd002
        containerPath: /mnt/hdd002
