kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: leilfs-operator
nodes:
  - role: control-plane

  # worker — hosts the LeilFS master (via nodeSelector leilfs-role=master)
  # and two chunk servers (one per disk).
  - role: worker
    extraMounts:
      - hostPath: /tmp/leilfs-kind/worker1/hdd001
        containerPath: /mnt/hdd001
      - hostPath: /tmp/leilfs-kind/worker1/hdd002
        containerPath: /mnt/hdd002

  # worker2 — two chunk servers (one per disk).
  - role: worker
    extraMounts:
      - hostPath: /tmp/leilfs-kind/worker2/hdd001
        containerPath: /mnt/hdd001
      - hostPath: /tmp/leilfs-kind/worker2/hdd002
        containerPath: /mnt/hdd002

  # worker3 — two chunk servers (one per disk).
  - role: worker
    extraMounts:
      - hostPath: /tmp/leilfs-kind/worker3/hdd001
        containerPath: /mnt/hdd001
      - hostPath: /tmp/leilfs-kind/worker3/hdd002
        containerPath: /mnt/hdd002
