# permissions for end users to view localdisks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: localdisk-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: localdisk-operator
    app.kubernetes.io/part-of: localdisk-operator
    app.kubernetes.io/managed-by: kustomize
  name: localdisk-viewer-role
rules:
- apiGroups:
  - disk.localdisk-operator.io
  resources:
  - localdisks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - disk.localdisk-operator.io
  resources:
  - localdisks/status
  verbs:
  - get
